/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vsas;

import javafx.application.Application;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import vsas.config.HikariCPConfig;
import vsas.config.MybatisConfig;
import vsas.controller.JumpPage;
import vsas.utils.DEFINE;

import java.util.Objects;


public class App extends Application {

    public static void main(String[] args) {
        coldStartUp();
        launch();
    }

    private static void coldStartUp(){
        MybatisConfig.getInstance();
        HikariCPConfig.getInstance();
    }

    @Override
    public void start(Stage primaryStage) throws Exception{

        primaryStage.setScene(JumpPage.getLoginScene());

        // set window's title
        primaryStage.setTitle("Virtual Scroll Access System");

        // Load and set the icon
        Image icon = new Image(Objects.requireNonNull(getClass().getResourceAsStream("/img/logo@2x.png")));
        primaryStage.getIcons().add(icon);

        // set width and height
        DEFINE.setWindowSize(primaryStage, DEFINE.PAGE_NAME_LOGIN);

        // forbidden change the size of stage
        primaryStage.setResizable(false);

        // show stage
        primaryStage.show();

    }
}
